baseURL = "https://thieenq.github.io/"
relativeURLs = true
uglyURLs = true

title = "Backlog Overload"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = "&copy; 2020 Hoang Tran"

theme = "pickles"
custom_css = "/static/css/custom.css"

#googleAnalytics = "Your Google Analytics tracking id"

enableRobotsTXT = true # generate robots.txt

[Taxonomies]
    tag = "tags"

[params]
  paginate = 10
  github = "thieenq"
  linkedin = "tthoang171"
#   twitter = "Your Twitter username"
#   facebook = "Your Facebook username"
#   instagram = "Your Instagram username"
#   googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
#   gitlab = "Your GitLab username"
#   npm = "Your npm username"
#   codepen = "Your CodePen username"
#   dribbble = "Your Dribbble username"
#   fivehundredpx = "Your 500px username" # 500px
#   flickr = "Your Flickr username"
#   pinterest = "Your Pinterest username"
#   tumblr = "Your Tumblr username"
#   vimeo = "Your Vimeo username"
#   youtube = "Your YouTube username"
#   medium = "Your Medium username"
#   disqus = "HT"

  subtitle = "data, tech, travel, opinions"

  author = "Hoang Tran"
  authorwebsite = "thieenq.github.io"
  avatar = "/images/avatar.jpg"
  contact = "mailto:thienhoang1608@gmail.com"
  bio = "I do data"
  logo = "/images/logo.png" # Logo image. This is displayed ogp image.
  favicon = "/favicon.ico"

[Permalinks]
    post = "/:slug"

[menu]
    [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

    [[menu.main]]
    weight = 2
    url = "/about.html"

languageCode = "en-uk"