name: CI
on:
  push:
    branchs:
      - hugo_gen

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        uses: TartanLlama/actions-eleventy@master

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: master
          # publish_branch: gh-pages
          # cname: example.com
          commit_message: ${{ github.event.head_commit.message }}
          install_dependencies: true
